//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblReunion
    {
        public int id_reunion { get; set; }
        [Required]
        public string title { get; set; }
        [Required]
        public Nullable<System.DateTime> fecha_y_hora { get; set; }
        [Required]
        public int id_user { get; set; }
        [Required]
        public bool esVirtual { get; set; }
        [Required]
        public int id_client { get; set; }
    }
}
